//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _147865546_3696430977078572_6210940146562061635_o {
            get {
                object obj = ResourceManager.GetObject("147865546_3696430977078572_6210940146562061635_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1581472982176_Pepsi_200212_0021 {
            get {
                object obj = ResourceManager.GetObject("1581472982176-Pepsi_200212_0021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _21 {
            get {
                object obj = ResourceManager.GetObject("21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _22 {
            get {
                object obj = ResourceManager.GetObject("22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23 {
            get {
                object obj = ResourceManager.GetObject("23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2df4611633794702b370f83202e3405b_1623127569732121253 {
            get {
                object obj = ResourceManager.GetObject("2df4611633794702b370f83202e3405b_1623127569732121253", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2df4611633794702b370f83202e3405b_16231275697321212531 {
            get {
                object obj = ResourceManager.GetObject("2df4611633794702b370f83202e3405b_16231275697321212531", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2df4611633794702b370f83202e3405b_16231275697321212532 {
            get {
                object obj = ResourceManager.GetObject("2df4611633794702b370f83202e3405b_16231275697321212532", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31 {
            get {
                object obj = ResourceManager.GetObject("31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32 {
            get {
                object obj = ResourceManager.GetObject("32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _33 {
            get {
                object obj = ResourceManager.GetObject("33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _34 {
            get {
                object obj = ResourceManager.GetObject("34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _706895 {
            get {
                object obj = ResourceManager.GetObject("706895", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap call_to_action {
            get {
                object obj = ResourceManager.GetObject("call-to-action", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cart {
            get {
                object obj = ResourceManager.GetObject("cart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__7_ {
            get {
                object obj = ResourceManager.GetObject("images (7)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kak_sdelat_gamburger {
            get {
                object obj = ResourceManager.GetObject("kak-sdelat-gamburger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mcdonaldsglobal {
            get {
                object obj = ResourceManager.GetObject("mcdonaldsglobal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mcdonaldsglobal1 {
            get {
                object obj = ResourceManager.GetObject("mcdonaldsglobal1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap password {
            get {
                object obj = ResourceManager.GetObject("password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap password1 {
            get {
                object obj = ResourceManager.GetObject("password1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cream_brown_vintage_wood_nature_background_texture_image_918033 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cream-brown-vintage-wood-nature-background-texture-image_918033", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cream_brown_vintage_wood_nature_background_texture_image_9180331 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cream-brown-vintage-wood-nature-background-texture-image_9180331", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cream_brown_vintage_wood_nature_background_texture_image_9180332 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cream-brown-vintage-wood-nature-background-texture-image_9180332", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cream_brown_vintage_wood_nature_background_texture_image_9180333 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cream-brown-vintage-wood-nature-background-texture-image_9180333", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cream_brown_vintage_wood_nature_background_texture_image_9180334 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cream-brown-vintage-wood-nature-background-texture-image_9180334", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cream_brown_vintage_wood_nature_background_texture_image_9180335 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cream-brown-vintage-wood-nature-background-texture-image_9180335", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cream_brown_vintage_wood_nature_background_texture_image_9180336 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cream-brown-vintage-wood-nature-background-texture-image_9180336", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cream_brown_vintage_wood_nature_background_texture_image_9180337 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cream-brown-vintage-wood-nature-background-texture-image_9180337", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qa1xal {
            get {
                object obj = ResourceManager.GetObject("qa1xal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_arrow {
            get {
                object obj = ResourceManager.GetObject("right-arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_arrow1 {
            get {
                object obj = ResourceManager.GetObject("right-arrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Super_Fries_K {
            get {
                object obj = ResourceManager.GetObject("Super-Fries_K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trolley_cart {
            get {
                object obj = ResourceManager.GetObject("trolley-cart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap คิววว {
            get {
                object obj = ResourceManager.GetObject("คิววว", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap คิวอาโค้ด {
            get {
                object obj = ResourceManager.GetObject("คิวอาโค้ด", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap งานนำเสนอ_การตลาด_การขาย_เรียบง่าย_สีเขียวและสีครีม {
            get {
                object obj = ResourceManager.GetObject("งานนำเสนอ การตลาด การขาย เรียบง่าย สีเขียวและสีครีม", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap งานนำเสนอ_การตลาด_การขาย_เรียบง่าย_สีเขียวและสีครีม__1_ {
            get {
                object obj = ResourceManager.GetObject("งานนำเสนอ การตลาด การขาย เรียบง่าย สีเขียวและสีครีม (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap งานนำเสนอ_การลงประกาศ_ผู้ซื้ออสังหาริมทรัพย์_บล็อก_เส้นทแยงมุม_สีเขียวเข้มและสีขาว {
            get {
                object obj = ResourceManager.GetObject("งานนำเสนอ การลงประกาศ ผู้ซื้ออสังหาริมทรัพย์ บล็อก เส้นทแยงมุม สีเขียวเข้มและสีขา" +
                        "ว", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap งานนำเสนอ_การลงประกาศ_ผู้ซื้ออสังหาริมทรัพย์_บล็อก_เส้นทแยงมุม_สีเขียวเข้มและสีขาว__1_ {
            get {
                object obj = ResourceManager.GetObject("งานนำเสนอ การลงประกาศ ผู้ซื้ออสังหาริมทรัพย์ บล็อก เส้นทแยงมุม สีเขียวเข้มและสีขา" +
                        "ว (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap งานนำเสนอ_การลงประกาศ_ผู้ซื้ออสังหาริมทรัพย์_บล็อก_เส้นทแยงมุม_สีเขียวเข้มและสีขาว__2_ {
            get {
                object obj = ResourceManager.GetObject("งานนำเสนอ การลงประกาศ ผู้ซื้ออสังหาริมทรัพย์ บล็อก เส้นทแยงมุม สีเขียวเข้มและสีขา" +
                        "ว (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap งานนำเสนอ_การศึกษา_บิงโก_มนุษย์_การละลายพฤติกรรมอุปกรณ์การเรียน_สีเหลืองและสีเขียว__1_ {
            get {
                object obj = ResourceManager.GetObject("งานนำเสนอ การศึกษา บิงโก มนุษย์ การละลายพฤติกรรมอุปกรณ์การเรียน สีเหลืองและสีเขีย" +
                        "ว (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap งานนำเสนอ_ภารกิจและเป้าหมาย_การดูแลสุขภาพ_ข้อเสนอ_ทันสมัย_ตัวหนา_สีเขียว {
            get {
                object obj = ResourceManager.GetObject("งานนำเสนอ ภารกิจและเป้าหมาย การดูแลสุขภาพ ข้อเสนอ ทันสมัย ตัวหนา สีเขียว", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap งานนำเสนอ_ภารกิจและเป้าหมาย_การดูแลสุขภาพ_ข้อเสนอ_ทันสมัย_ตัวหนา_สีเขียว__1_ {
            get {
                object obj = ResourceManager.GetObject("งานนำเสนอ ภารกิจและเป้าหมาย การดูแลสุขภาพ ข้อเสนอ ทันสมัย ตัวหนา สีเขียว (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ภาพขนาดย่อ_ยูทูบ_อาหาร_เจิดจ้า_สีพีชและสีแดง {
            get {
                object obj = ResourceManager.GetObject("ภาพขนาดย่อ ยูทูบ อาหาร เจิดจ้า สีพีชและสีแดง", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap มันบด2 {
            get {
                object obj = ResourceManager.GetObject("มันบด2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ลงทะเบียน {
            get {
                object obj = ResourceManager.GetObject("ลงทะเบียน", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ลงทะเบียน1 {
            get {
                object obj = ResourceManager.GetObject("ลงทะเบียน1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ลงทะเบียน2 {
            get {
                object obj = ResourceManager.GetObject("ลงทะเบียน2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap สไลด์กำหนดการประจำวัน_ภาพประกอบ_สีชมพูและสีครีม {
            get {
                object obj = ResourceManager.GetObject("สไลด์กำหนดการประจำวัน ภาพประกอบ สีชมพูและสีครีม", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap สีเขียว_สีม่วง_แนวคิดดิจิทัล_เรียบง่าย_พื้นฐาน_งานนำเสนอ {
            get {
                object obj = ResourceManager.GetObject("สีเขียว สีม่วง แนวคิดดิจิทัล เรียบง่าย พื้นฐาน งานนำเสนอ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap สีเขียว_สีม่วง_แนวคิดดิจิทัล_เรียบง่าย_พื้นฐาน_งานนำเสนอ1 {
            get {
                object obj = ResourceManager.GetObject("สีเขียว สีม่วง แนวคิดดิจิทัล เรียบง่าย พื้นฐาน งานนำเสนอ1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap สีดำ_สีเขียว_แนวคิดดิจิทัล_พื้นฐาน_เรียบง่าย_งานนำเสนอ {
            get {
                object obj = ResourceManager.GetObject("สีดำ สีเขียว แนวคิดดิจิทัล พื้นฐาน เรียบง่าย งานนำเสนอ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
